# Generated by Django 6.1 on 2026-08-18 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('es_alimento', models.BooleanField(default=True)),
                ('tipo_ganancia_default', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo USD')], default='PORCENTAJE', max_length=15)),
                ('valor_ganancia_default', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_redondeo', models.IntegerField(default=20)),
                ('porcentaje_emergencia_bcv', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones del Negocio',
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('moneda', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tasa_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_margen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('moneda_compra', models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares')], max_length=3)),
                ('moneda_venta', models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares')], default='VES', max_length=3)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kg_por_saco', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('usar_ganancia_categoria', models.BooleanField(default=True)),
                ('tipo_ganancia_personalizada', models.CharField(blank=True, choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo USD')], max_length=15, null=True)),
                ('valor_ganancia_personalizada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_en_almacen', models.IntegerField(default=0)),
                ('cantidad_en_tienda', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIngresoSaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_sacos_vendidos', models.IntegerField()),
                ('ingreso_bruto_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
