# Generated by Django 6.1 on 2026-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='tipo_aumento_bcv',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo USD/Bs'), ('MANUAL', 'Manual')], default='PORCENTAJE', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='valor_aumento_bcv',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
