# Generated by Django 6.1 on 2026-08-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_configuracionnegocio_tipo_aumento_bcv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='es_alimento',
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICINA', 'Medicina'), ('ACCESORIO', 'Accesorio')], default='ALIMENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo_ganancia_mayor_default',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo USD')], default='PORCENTAJE', max_length=15),
        ),
        migrations.AddField(
            model_name='categoria',
            name='valor_ganancia_mayor_default',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='se_vende_al_mayor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_ganancia_mayor_personalizada',
            field=models.CharField(blank=True, choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo USD')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='usar_ganancia_categoria_mayor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_ganancia_mayor_personalizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
