# Generated by Django 6.1 on 2026-08-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_categoria_se_vende_al_mayor_default_ventamayor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='kg_por_saco',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_ganancia_mayor_personalizada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usar_ganancia_categoria_mayor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor_ganancia_mayor_personalizada',
        ),
        migrations.AddField(
            model_name='producto',
            name='medida_cantidad_porcion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida_cantidad_total',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_mayor_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('GR', 'Gramos'), ('UNIDAD', 'Unidades')], default='UNIDAD', max_length=10),
        ),
    ]
