# Generated by Django 6.1 on 2026-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_producto_kg_por_saco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta_mayor_usd',
            new_name='precio_venta_mayor_usd_bcv',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_mayor_usd_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
