# Generated by Django 6.1 on 2026-08-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimientoinventario_ventadetal_detalleventadetal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_en_almacen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_en_tienda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
