# Generated by Django 6.1 on 2026-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_producto_cantidad_en_almacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='redondear_usd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='redondear_ves',
            field=models.BooleanField(default=True),
        ),
    ]
