# Generated by Django 6.1 on 2026-08-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_configuracionnegocio_redondear_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='valor_redondeo_usd',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='valor_redondeo_ves',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
