# Generated by Django 6.1 on 2026-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_categoria_nombre_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='aumento_bcv_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='aumento_usdt_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='tipo_aumento_usdt',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('FIJO', 'Monto Fijo USD/Bs'), ('MANUAL', 'Manual')], default='PORCENTAJE', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='valor_aumento_usdt',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
