# Generated by Django 6.1 on 2026-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_configuracionnegocio_aumento_bcv_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamayor',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DOLARES_BCV', 'Dólares a BCV')], default='EFECTIVO', max_length=20),
        ),
    ]
