# Generated by Django 6.1 on 2026-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_ventamayor_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventamayor',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='detalleventamayor',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DOLARES_BCV', 'Dólares a BCV')], default='EFECTIVO', max_length=20),
        ),
    ]
