# Generated by Django 6.1 on 2026-08-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_metodopago_cierrediario_detallecierrediario'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares ($)'), ('VES', 'Bolívares (Bs)')], default='USD', max_length=3),
        ),
    ]
