# Generated by Django 6.1 on 2026-08-21 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_metodopago_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrediario',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='detallecierrediario',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ventamayor',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleventamayor',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DOLARES_BCV', 'Dólares a BCV'), ('CREDITO', 'Crédito')], default='EFECTIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='AbonoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='inventario.ventamayor')),
            ],
        ),
    ]
