# Generated by Django 6.1 on 2026-08-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_cierrediario_tasa_bcv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamayor',
            name='es_credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleventamayor',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DOLARES_BCV', 'Dólares a BCV')], default='EFECTIVO', max_length=20),
        ),
    ]
