# Generated by Django 6.1 on 2026-08-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_ventamayor_es_credito_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroIngresoSaco',
        ),
    ]
