# Generated by Django 6.1 on 2026-08-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_delete_registroingresosaco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='moneda_compra',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares')], max_length=20),
        ),
    ]
