# Generated by Django 6.1 on 2026-08-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_alter_producto_moneda_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='moneda_compra',
            field=models.CharField(max_length=20),
        ),
    ]
